// lib/niches.js
// Central config for all niches.
// Add a new niche here + drop its JSON file in /data/ — pages generate automatically.

export const NICHES = [
  {
    slug: 'driving-schools',
    label: 'Driving Schools',
    description: 'Find accredited K53 driving schools near you in Johannesburg and Gauteng.',
    icon: '🚗',
    dataFile: 'driving-schools.json',
    searchKeywords: ['driving school', 'k53', 'learners licence', 'drivers licence'],
  },
  {
    slug: 'solar-inverter-installers',
    label: 'Solar & Inverter Installers',
    description: 'Compare solar panel and inverter backup installers across Gauteng.',
    icon: '☀️',
    dataFile: 'solar-inverter-installers.json',
    searchKeywords: ['solar panels', 'inverter installer', 'backup power', 'load shedding'],
  },
  {
    slug: 'dog-groomers',
    label: 'Dog Groomers',
    description: 'Find trusted dog groomers and pet grooming salons near you in Joburg.',
    icon: '🐾',
    dataFile: 'dog-groomers.json',
    searchKeywords: ['dog groomer', 'pet grooming', 'dog wash', 'dog salon'],
  },
  {
    slug: 'panel-beaters',
    label: 'Panel Beaters',
    description: 'Panel beaters and auto body repair shops in Johannesburg and Gauteng.',
    icon: '🔧',
    dataFile: 'panel-beaters.json',
    searchKeywords: ['panel beater', 'auto body repair', 'car dent repair', 'accident repair'],
  },
  {
    slug: 'phone-repair-shops',
    label: 'Phone Repair Shops',
    description: 'Screen repairs, battery replacements and phone repairs near you in Joburg.',
    icon: '📱',
    dataFile: 'phone-repair-shops.json',
    searchKeywords: ['phone repair', 'screen repair', 'iphone repair', 'samsung repair'],
  },
  {
    slug: 'air-conditioning-installers',
    label: 'Air Conditioning Installers',
    description: 'Air conditioning installation and repair services in Johannesburg and Gauteng.',
    icon: '❄️',
    dataFile: 'air-conditioning-installers.json',
    searchKeywords: ['air conditioning installation', 'aircon installer', 'hvac', 'split unit installation'],
  },
  {
    slug: 'auto-electricians',
    label: 'Auto Electricians',
    description: 'Auto electricians and vehicle electrical repairs across Johannesburg.',
    icon: '⚡',
    dataFile: 'auto-electricians.json',
    searchKeywords: ['auto electrician', 'car electrician', 'vehicle electrical', 'auto electrical'],
  },
  {
    slug: 'barbers',
    label: 'Barbers',
    description: 'Find top barbershops and barbers near you in Johannesburg.',
    icon: '✂️',
    dataFile: 'barbers.json',
    searchKeywords: ['barber', 'barbershop', 'mens haircut', 'hair cut'],
  },
  {
    slug: 'car-detailing',
    label: 'Car Detailing',
    description: 'Professional car detailing and valeting services in Johannesburg.',
    icon: '🚘',
    dataFile: 'car-detailing.json',
    searchKeywords: ['car detailing', 'car polish', 'auto detailing', 'car valet'],
  },
  {
    slug: 'carpet-upholstery-cleaning',
    label: 'Carpet & Upholstery Cleaning',
    description: 'Carpet and upholstery cleaning services across Johannesburg and Gauteng.',
    icon: '🧹',
    dataFile: 'carpet-upholstery-cleaning.json',
    searchKeywords: ['carpet cleaning', 'upholstery cleaning', 'couch cleaning', 'carpet wash'],
  },
  {
    slug: 'cctv-camera-installers',
    label: 'CCTV & Camera Installers',
    description: 'CCTV and security camera installation in Johannesburg and Gauteng.',
    icon: '📷',
    dataFile: 'cctv-camera-installers.json',
    searchKeywords: ['cctv installation', 'security camera installer', 'cctv installer', 'surveillance cameras'],
  },
  {
    slug: 'debt-review-consultants',
    label: 'Debt Review Consultants',
    description: 'Registered debt review and debt counselling consultants in Johannesburg.',
    icon: '💳',
    dataFile: 'debt-review-consultants.json',
    searchKeywords: ['debt review', 'debt counselling', 'debt consolidation', 'debt review consultant'],
  },
  {
    slug: 'domestic-cleaning-services',
    label: 'Domestic Cleaning Services',
    description: 'Domestic and home cleaning services across Johannesburg and Gauteng.',
    icon: '🏠',
    dataFile: 'domestic-cleaning-services.json',
    searchKeywords: ['domestic cleaning', 'house cleaning', 'home cleaning service', 'domestic worker'],
  },
  {
    slug: 'dog-kennels-boarding',
    label: 'Dog Kennels & Boarding',
    description: 'Dog kennels, boarding and pet daycare facilities in Johannesburg.',
    icon: '🐕',
    dataFile: 'dog-kennels-boarding.json',
    searchKeywords: ['dog kennel', 'dog boarding', 'pet boarding', 'dog daycare'],
  },
  {
    slug: 'dstv-installers',
    label: 'DSTV Installers',
    description: 'Accredited DSTV installers and satellite dish services in Johannesburg.',
    icon: '📡',
    dataFile: 'dstv-installers.json',
    searchKeywords: ['dstv installation', 'dstv installer', 'satellite dish', 'dstv accredited installer'],
  },
  {
    slug: 'electric-fence-installers',
    label: 'Electric Fence Installers',
    description: 'Electric fence installation and repairs in Johannesburg and Gauteng.',
    icon: '🔌',
    dataFile: 'electric-fence-installers.json',
    searchKeywords: ['electric fence installation', 'electric fence installer', 'security fence', 'electric fencing'],
  },
  {
    slug: 'electricians',
    label: 'Electricians',
    description: 'Qualified electricians for residential and commercial work in Johannesburg.',
    icon: '💡',
    dataFile: 'electricians.json',
    searchKeywords: ['electrician', 'electrical contractor', 'electrical repairs', 'electrical installation'],
  },
  {
    slug: 'furniture-removal',
    label: 'Furniture Removal',
    description: 'Furniture removal and relocation companies in Johannesburg and Gauteng.',
    icon: '🚚',
    dataFile: 'furniture-removal.json',
    searchKeywords: ['furniture removal', 'moving company', 'furniture movers', 'relocation'],
  },
  {
    slug: 'garden-services',
    label: 'Garden Services',
    description: 'Garden services, landscaping and lawn maintenance across Johannesburg.',
    icon: '🌿',
    dataFile: 'garden-services.json',
    searchKeywords: ['garden services', 'gardener', 'landscaping', 'lawn maintenance'],
  },
  {
    slug: 'gate-motor-repairs',
    label: 'Gate Motor Repairs',
    description: 'Gate motor repairs, installation and servicing in Johannesburg.',
    icon: '🚪',
    dataFile: 'gate-motor-repairs.json',
    searchKeywords: ['gate motor repair', 'gate motor installation', 'automatic gate', 'gate motor service'],
  },
  {
    slug: 'generator-repair-service',
    label: 'Generator Repair & Service',
    description: 'Generator repairs, servicing and installation in Johannesburg and Gauteng.',
    icon: '🔋',
    dataFile: 'generator-repair-service.json',
    searchKeywords: ['generator repair', 'generator service', 'generator maintenance', 'generator installation'],
  },
  {
    slug: 'geyser-repair-replacement',
    label: 'Geyser Repair & Replacement',
    description: 'Geyser repairs, replacement and installation across Johannesburg.',
    icon: '🚿',
    dataFile: 'geyser-repair-replacement.json',
    searchKeywords: ['geyser repair', 'geyser replacement', 'geyser installation', 'hot water cylinder'],
  },
  {
    slug: 'hair-salons',
    label: 'Hair Salons',
    description: 'Hair salons and hairdressers near you in Johannesburg and Gauteng.',
    icon: '💇',
    dataFile: 'hair-salons.json',
    searchKeywords: ['hair salon', 'hairdresser', 'hair stylist', 'beauty salon'],
  },
  {
    slug: 'jumping-castle-hire',
    label: 'Jumping Castle Hire',
    description: 'Jumping castle and bouncy castle hire for parties in Johannesburg.',
    icon: '🏰',
    dataFile: 'jumping-castle-hire.json',
    searchKeywords: ['jumping castle hire', 'bouncy castle hire', 'party hire', 'jumping castle rental'],
  },
  {
    slug: 'kids-party-venues',
    label: 'Kids Party Venues',
    description: 'Kids birthday party venues across Johannesburg and Gauteng.',
    icon: '🎉',
    dataFile: 'kids-party-venues.json',
    searchKeywords: ['kids party venue', 'childrens party venue', 'birthday party venue', 'party venue kids'],
  },
  {
    slug: 'laptop-pc-repair',
    label: 'Laptop & PC Repair',
    description: 'Laptop and computer repairs across Johannesburg and Gauteng.',
    icon: '💻',
    dataFile: 'laptop-pc-repair.json',
    searchKeywords: ['laptop repair', 'pc repair', 'computer repair', 'laptop screen repair'],
  },
  {
    slug: 'mobile-beauty-therapists',
    label: 'Mobile Beauty Therapists',
    description: 'Mobile beauty therapists and at-home beauty services in Johannesburg.',
    icon: '💆',
    dataFile: 'mobile-beauty-therapists.json',
    searchKeywords: ['mobile beauty therapist', 'mobile beauty', 'beauty therapist', 'mobile spa'],
  },
  {
    slug: 'nail-bars',
    label: 'Nail Bars',
    description: 'Nail bars and nail salons near you in Johannesburg and Gauteng.',
    icon: '💅',
    dataFile: 'nail-bars.json',
    searchKeywords: ['nail bar', 'nail salon', 'nail technician', 'acrylic nails'],
  },
  {
    slug: 'pest-control',
    label: 'Pest Control',
    description: 'Pest control and fumigation services across Johannesburg and Gauteng.',
    icon: '🐛',
    dataFile: 'pest-control.json',
    searchKeywords: ['pest control', 'pest exterminator', 'fumigation', 'termite control'],
  },
  {
    slug: 'plumbers',
    label: 'Plumbers',
    description: 'Qualified plumbers for residential and commercial work in Johannesburg.',
    icon: '🪠',
    dataFile: 'plumbers.json',
    searchKeywords: ['plumber', 'plumbing services', 'burst pipe', 'geyser repair plumber'],
  },
  {
    slug: 'school-uniform-suppliers',
    label: 'School Uniform Suppliers',
    description: 'School uniform suppliers and shops across Johannesburg and Gauteng.',
    icon: '🎒',
    dataFile: 'school-uniform-suppliers.json',
    searchKeywords: ['school uniform', 'school uniform supplier', 'school clothes', 'school uniform shop'],
  },
  {
    slug: 'shisa-nyama',
    label: 'Shisa Nyama',
    description: 'Find the best shisa nyama spots and braai restaurants in Johannesburg.',
    icon: '🔥',
    dataFile: 'shisa-nyama.json',
    searchKeywords: ['shisa nyama', 'shisanyama', 'braai restaurant', 'township braai'],
  },
  {
    slug: 'smash-grab-tinting',
    label: 'Smash & Grab Tinting',
    description: 'Smash and grab window tinting for vehicles in Johannesburg.',
    icon: '🪟',
    dataFile: 'smash-grab-tinting.json',
    searchKeywords: ['smash and grab tinting', 'window tinting', 'car tinting', 'smash grab film'],
  },
  {
    slug: 'tree-felling',
    label: 'Tree Felling',
    description: 'Tree felling, removal and trimming services in Johannesburg and Gauteng.',
    icon: '🌳',
    dataFile: 'tree-felling.json',
    searchKeywords: ['tree felling', 'tree removal', 'tree cutting', 'tree trimming'],
  },
  {
    slug: 'vets',
    label: 'Vets',
    description: 'Find trusted vets and veterinary clinics near you in Johannesburg.',
    icon: '🐾',
    dataFile: 'vets.json',
    searchKeywords: ['vet', 'veterinarian', 'animal hospital', 'veterinary clinic'],
  },
  {
    slug: 'waterproofing-damp-proofing',
    label: 'Waterproofing & Damp Proofing',
    description: 'Waterproofing and damp proofing specialists in Johannesburg and Gauteng.',
    icon: '💧',
    dataFile: 'waterproofing-damp-proofing.json',
    searchKeywords: ['waterproofing', 'damp proofing', 'roof waterproofing', 'damp specialist'],
  },
  {
    slug: 'windscreen-replacement',
    label: 'Windscreen Replacement',
    description: 'Windscreen replacement and auto glass repairs in Johannesburg.',
    icon: '🚗',
    dataFile: 'windscreen-replacement.json',
    searchKeywords: ['windscreen replacement', 'windscreen repair', 'auto glass', 'windshield replacement'],
  },
]

export function getNicheBySlug(slug) {
  return NICHES.find(n => n.slug === slug) || null
}
